[package]
name = "pastasus/secure-data-and-inventory-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
